# Generated by Django 5.2.7 on 2025-10-04 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='petition_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('votes', models.ManyToManyField(blank=True, related_name='petition_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
